M48
; DRILL file KiCad 10.0.6 date 2026-09-07T22:25:18
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-07T22:25:18+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X122.5Y-92.0
X122.5Y-101.0
T2
X105.0Y-54.5
X105.0Y-165.0
X140.0Y-165.0
X141.5Y-84.0
T3
X122.5Y-81.0
M30
